/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // Original HealLink purple palette (dominant)
        "background":               "#f8f9fc",
        "surface":                  "#f8f9fc",
        "surface-bright":           "#f8f9fc",
        "surface-dim":              "#d9dadd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low":    "#f2f3f6",
        "surface-container":        "#edeef1",
        "surface-container-high":   "#e7e8eb",
        "surface-container-highest":"#e1e2e5",
        "surface-variant":          "#e1e2e5",
        "on-surface":               "#191c1e",
        "on-surface-variant":       "#484555",
        "on-background":            "#191c1e",
        "primary":                  "#532cd8",
        "primary-container":        "#6c4cf1",
        "primary-fixed":            "#e6deff",
        "primary-fixed-dim":        "#c9beff",
        "on-primary":               "#ffffff",
        "on-primary-container":     "#f0eaff",
        "on-primary-fixed":         "#1b0062",
        "on-primary-fixed-variant": "#4616cc",
        "inverse-primary":          "#c9beff",
        "secondary":                "#613ed3",
        "secondary-container":      "#7a5aee",
        "secondary-fixed":          "#e7deff",
        "secondary-fixed-dim":      "#cbbeff",
        "on-secondary":             "#ffffff",
        "on-secondary-container":   "#fffbff",
        "on-secondary-fixed":       "#1e0061",
        "on-secondary-fixed-variant":"#4b20bd",
        "tertiary":                 "#50535d",
        "tertiary-container":       "#686b75",
        "tertiary-fixed":           "#e0e2ee",
        "tertiary-fixed-dim":       "#c4c6d2",
        "on-tertiary":              "#ffffff",
        "on-tertiary-container":    "#ebedf9",
        "on-tertiary-fixed":        "#181b24",
        "on-tertiary-fixed-variant":"#434750",
        "outline":                  "#797587",
        "outline-variant":          "#c9c4d8",
        "surface-tint":             "#5f3ce4",
        "inverse-surface":          "#2e3133",
        "inverse-on-surface":       "#f0f1f4",
        "error":                    "#ba1a1a",
        "on-error":                 "#ffffff",
        "error-container":          "#ffdad6",
        "on-error-container":       "#93000a",
        // Tender Smiles gold accent
        "ts-gold":                  "#F5B53F",
        "ts-gold-light":            "#FEF3D8",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:   "1rem",
        xl:   "1.5rem",
        "2xl":"2rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
